# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161015_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modification_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modification_time',
            field=models.DateField(auto_now=True),
        ),
    ]
