# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161016_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modification_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
